export const CONFIG = {
  NEXT_PUBLIC_EMAIL_SERVICE_ID: process.env.NEXT_PUBLIC_EMAIL_SERVICE_ID ?? '',
  NEXT_PUBLIC_EMAIL_TEMPLATE_ID: process.env.NEXT_PUBLIC_EMAIL_TEMPLATE_ID ?? '',
  NEXT_PUBLIC_EMAIL_FULL_TEMPLATE_ID: process.env.NEXT_PUBLIC_EMAIL_FULL_TEMPLATE_ID ?? '',
  NEXT_PUBLIC_EMAIL_KEY: process.env.NEXT_PUBLIC_EMAIL_KEY ?? '',
};
