export const TEXT = {
  PROJECT_TITLE: 'Client Blog',
  PROJECT_DESCRIPTION: 'We are a community of content writers who share their learnings',

  ENGLISH: 'en',
  RUSSIAN: 'ru',

  HEADER: 'Modsen Client Blog',
  VIDEO_BUTTON: 'Video',

  FOOTER_TITLE: 'Title',
  ADDRES: 'Finstreet 118 2561 Fintown',
  EMAIL: 'Hello@finsweet.com 020 7993 2905',
  SUBSCRIBE: 'Subscribe',
  SUBSCRIBE_OK: 'Subscribe Ok',

  SUBSCRIBE_ERROR: 'Subscribe error',
  EMAIL_ERROR: 'Invalid email',

  EMAIL_PLACEHOLDER: 'Email placeholder',

  POSTED: 'Posted',
  BY: 'By',
  READ_MORE: 'Read more',
  FEATURE_POST: 'Feature Post',
  VIEW_ALL: 'View all',
  ABOUT_US: 'About us',
  MISION: 'Our mision',
  ABOUT_US_TITLE: 'About title',
  ABOUT_TEXT: 'About text',
  MISION_TITLE: 'Mision title',
  MISION_TEXT: 'Mision text',
  VISION: 'Our vision',
  VISION_TITLE: 'Vision title',
  CHOOSE_CATEGORY: 'Choose A Catagory',
  WE_STARTED: 'We started',
  WE_STARTED_HEADER: 'We started header',
  WE_STARTED_TEXT: 'We started text',
  DISCOVER: 'Discover',
  AUTHORS: 'Authors',
  WRITTER: 'Content Writer',
  WE: 'We',
  FEATURED_IN: 'Featured in',
  JOIN_HEADER: 'Join header',
  JOIN_TEXT: 'Join text',
  JOUN_BUTTON: 'Join button',
  TESTIMONIAL: 'TESTIMONIAL',
  TESTIMONIAL_TEXT: 'TESTIMONIAL text',
  TESTIMONIAL_TITLE: 'TESTIMONIAL title',

  BLOG_PUBLISHED: 'Blog Published',
  VIEW_FIN: 'Views on Finsweet',
  ACTIVE_USER: 'Total active Users',

  ALL_CATEGORIES: 'All Categories',
  ALL_POST: 'All posts',
  NEXT: 'Next >',
  PREV: 'Prev >',

  ABOUT_TEAM: 'About team',
  ABOUT_BLOG: 'About blog',
  ABOUT_SUBTITLE: 'About subtitle',
  ABOUT_CONTENT: 'About text',

  POST_ALT: 'Post alt',

  PRIVACY_POLICY: 'Privacy Policy',
  LAST_UPDATED: 'Last Updated',
  POLICY_TITLE_TOP: 'Policy title top',
  POLICY_TITLE_BOTTOM: 'Policy title bottom',
  POLICY_TEXT_TOP: 'Policy text top',
  POLICY_TEXT_BOTTOM: 'Policy text bottom',

  MY_POSTS: 'My posts',
  NO_POST: 'No posts',

  NOT_FOUND: 'Not found',
  HELLO: 'Hello',
  WELCOM: 'Welcom',
};
