export const TEXT = {
  PROJECT_TITLE: 'Client Blog',
  PROJECT_DESCRIPTION: 'We are a community of content writers who share their learnings',

  ENGLISH: 'en',
  RUSSIAN: 'ru',

  HEADER: 'Modsen Client Blog',
  VIDEO_BUTTON: 'Video',

  FOOTER_TITLE: 'Title',
  ADDRES: 'Finstreet 118 2561 Fintown',
  EMAIL: 'Hello@finsweet.com',
  PHONE: '020 7993 2905',
  SUBSCRIBE: 'Subscribe',
  SUBSCRIBE_OK: 'Subscribe Ok',

  SUBSCRIBE_ERROR: 'Subscribe error',
  EMAIL_ERROR: 'Invalid email',

  EMAIL_PLACEHOLDER: 'Email placeholder',
  FULL_EMAIL_PLACEHOLDER: 'Full email',
  NAME_PLACEHOLDER: 'Name placeholder',
  QUERY_PLACEHOLDER: 'Query Related',
  MESSAGE_PLACEHOLDER: 'Message placeholder',
  SEND: 'Send',
  CONTACT_ERROR: 'Contact error',
  SENDING: 'Sending',
  SENDING_OK: 'Sending ok',

  NAME_REQUIRED: 'name is a required field',
  EMAIL_REQUIRED: 'email is a required field',
  QUERY_REQUIRED: 'query is a required field',
  MESSAGE_REQUIRED: 'message is a required field',

  POSTED: 'Posted',
  BY: 'By',
  READ_MORE: 'Read more',
  FEATURE_POST: 'Feature Post',
  VIEW_ALL: 'View all',
  ABOUT_US: 'About us',
  MISION: 'Our mision',
  ABOUT_US_TITLE: 'About title',
  ABOUT_TEXT: 'About text',
  MISION_TITLE: 'Mision title',
  MISION_TEXT: 'Mision text',
  VISION: 'Our vision',
  VISION_TITLE: 'Vision title',
  CHOOSE_CATEGORY: 'Choose A Catagory',
  WE_STARTED: 'We started',
  WE_STARTED_HEADER: 'We started header',
  WE_STARTED_TEXT: 'We started text',
  DISCOVER: 'Discover',
  AUTHORS: 'Authors',
  WRITTER: 'Content Writer',
  WE: 'We',
  FEATURED_IN: 'Featured in',
  JOIN_HEADER: 'Join header',
  JOIN_TEXT: 'Join text',
  JOUN_BUTTON: 'Join button',
  TESTIMONIAL: 'TESTIMONIAL',
  TESTIMONIAL_TEXT: 'TESTIMONIAL text',
  TESTIMONIAL_TITLE: 'TESTIMONIAL title',

  BLOG_PUBLISHED: 'Blog Published',
  BLOG_PUBLISHED_NUMBER: '12+',
  VIEW_FIN: 'Views on Finsweet',
  VIEW_FIN_NUMBER: '18K+',
  ACTIVE_USER: 'Total active Users',
  ACTIVE_USER_NUMBER: '30K+',

  ALL_CATEGORIES: 'All Categories',
  ALL_POST: 'All posts',
  NEXT: 'Next >',
  PREV: 'Prev >',

  ABOUT_TEAM: 'About team',
  ABOUT_BLOG: 'About blog',
  ABOUT_SUBTITLE: 'About subtitle',
  ABOUT_CONTENT: 'About text',

  POST_ALT: 'Post alt',
  AUTHOR_ALT: 'Author alt',
  PEOPLE_ALT: 'People alt',
  USER_ALT: 'User alt',

  PRIVACY_POLICY: 'Privacy Policy',
  LAST_UPDATED: 'Last Updated',
  POLICY_TITLE_TOP: 'Policy title top',
  POLICY_TITLE_BOTTOM: 'Policy title bottom',
  POLICY_TEXT_TOP: 'Policy text top',
  POLICY_TEXT_BOTTOM: 'Policy text bottom',

  MY_POSTS: 'My posts',
  NO_POST: 'No posts',
  POSTED_ON: 'Posted on',
  READ_NEXT: 'What to read next',

  NOT_FOUND: 'Not found',
  HELLO: 'Hello',
  WELCOM: 'Welcom',
  BLOG: 'Blog',

  CONTACT_US: 'Contact us',
  LET_START: 'let start',
  CONTACTS_TEXT: 'Contact text',
  WORKING_HOURS: 'Working hours',
  WORKING_DAYS: 'Working days',
  WORKING_TIME: 'Working time',
  SUPPORT: 'Support',

  ALL_TAGS: 'All tags',
  NO_TAGS: 'No tags',
  SEARCH_TAGS: 'Search tags',
  CATEGORIES: 'Categories',

  ERROR: 'Error',
};
